### ISSUE TITLE
Generate blurred out and 0 start parts 0 parts and 0 finish parts  

### ISSUE THREAD

**Issue by Shifu74** [RuurdBijlsma/tm-macro-track-generator#2]
![image](https://user-images.githubusercontent.com/120729304/216443085-dca63de6-b3b8-4ce0-9702-b15eb6e8f5a5.png)

**Comment by RuurdBijlsma** [comment]
the parts tab shows why parts are excluded, can you show that

**Comment by Shifu74** [comment]
![image1](https://user-images.githubusercontent.com/120729304/216444464-a4caae25-5148-4d04-9a76-3777836b85bc.png)

**Comment by RuurdBijlsma** [comment]
hmm did you delete the .MacroBlock.Gbx files from C:\Users\name\Documents\Trackmania\Blocks\Stadium\zzz_MacroTrackGenerator ? or did you just install the plugin and didnt restart the game since

**Comment by Shifu74** [comment]
![image2](https://user-images.githubusercontent.com/120729304/216445922-b929c7e5-bfc9-448c-bb64-e8bc329c93c0.png)
![image3](https://user-images.githubusercontent.com/120729304/216445984-8be98acd-8641-46ef-8d0a-6b32fc15463f.png)
after restrating still blurred out . Where should the .MacroBlock.Gbx be i checked every folder and there isnt one

**Comment by RuurdBijlsma** [comment]
hmm, there should be multiple macroblock files in each of those folders. Are there any errors in the console? (openplanet menu > log)

**Comment by RuurdBijlsma** [comment]
You could try deleting the zzz_macrotrackgenerator folder and restarting the game with the plugin installed, it should bring them back if they're not there

**Comment by Shifu74** [comment]
there seems to be no errors and deleting the folder and restarting the game doesn't seem to fix anything
![image15](https://user-images.githubusercontent.com/120729304/216448953-5ba47d86-a990-4e24-8477-607bed431d51.png)
![13](https://user-images.githubusercontent.com/120729304/216448955-641c4f60-6be7-477e-b32e-041e858594c4.png)
![14](https://user-images.githubusercontent.com/120729304/216448956-87338855-aa58-4978-b143-e1b8c33b5fa0.png)
![image1](https://user-images.githubusercontent.com/120729304/216448957-7a5f7747-a2c2-4cc8-9688-92bb9dc72b71.png)
![image4](https://user-images.githubusercontent.com/120729304/216448959-b23a037a-fdac-4ef0-b8bb-2ed7871755ca.png)
![image5](https://user-images.githubusercontent.com/120729304/216448962-03a227a0-7627-4cca-b6a2-285bcfe687b7.png)
![image6](https://user-images.githubusercontent.com/120729304/216448963-7b2857d4-9cfd-46a2-8317-0453288341f0.png)
![image7](https://user-images.githubusercontent.com/120729304/216448966-b949c24d-682a-41f5-aa0f-405b3f9d16af.png)
![image8](https://user-images.githubusercontent.com/120729304/216448970-4abb7d7a-0d18-412f-855f-915ac5f5128d.png)
![image10](https://user-images.githubusercontent.com/120729304/216448973-16630e23-ab06-458d-8a87-ba4a03d793f1.png)
![image11](https://user-images.githubusercontent.com/120729304/216448975-62fe59ab-4310-4f04-ab9c-7489d17fc88b.png)
![image12](https://user-images.githubusercontent.com/120729304/216448977-9379e192-9821-4ff6-9d71-378ed3cb60e5.png)
here is the inside of every folder

**Comment by Shifu74** [comment]
![Error](https://user-images.githubusercontent.com/120729304/216449372-2c1a4395-b1ba-4642-b107-cc73573d6e98.png)
i found this error in the log

**Comment by RuurdBijlsma** [comment]
just to be sure, you said before " Where should the .MacroBlock.Gbx be i checked every folder and there isnt one", the macroblocks are there in the screenshots now, is that new? or were they there before. If they are new you should restart game, otherwise I have no idea. I'll try reinstalling the plugin for myself to see if i notice anything wrong

**Comment by Shifu74** [comment]
They were there before also i just didn't understand you were talking about those

**Comment by Shifu74** [comment]
i have also tried uninstalling openplanet maybe could deleting openplanet temp files and logs?

**Comment by Shifu74** [comment]
also do you have any idea what caused the error cause i was just using it and then randomly a couple weeks ago it stopped working

**Comment by Shifu74** [comment]
maybe i should try fully deleting openplanet like every log and file it has ever made to reset everything?
also could the error be generated from another plugin interferring with the code?

**Comment by Shifu74** [comment]
Even after completly wiping openplanet and reintalling TM issue still continus

**Comment by RuurdBijlsma** [comment]
it's actually broken for me as well. I'm looking into it. When did it last work for you? May be some tm update broke it

**Comment by RuurdBijlsma** [comment]
oooh the structure of the macroblocks folder changed in a tm update, there's Official and Custom now. so it can't find the macroparts anymore. fixed it. Thx for reporting it :)

**Comment by RuurdBijlsma** [comment]
I uploaded the fix, will be published soon

**Comment by Shifu74** [comment]
Thank you
