### ISSUE TITLE
Generate only possible with game language set to english

### ISSUE THREAD

**Issue by Fallyx** [RuurdBijlsma/tm-macro-track-generator#3]
With your changes from #2 it is possible to use the plugin again, but only if the game language is set to english.
The "custom" folder wont be found in other languages, since the folder name is translated.
See: https://github.com/RuurdBijlsma/tm-macro-track-generator/blob/master/src/Generate/GenerateMethods.as#L139

**Comment by RuurdBijlsma** [comment]
Oh right oops, I'll fix it

**Comment by RuurdBijlsma** [comment]
fixed it in https://github.com/RuurdBijlsma/tm-macro-track-generator/commit/f9684394a038ef43baf54a47be657f2e44765e52 will be published when signed
